### ISSUE TITLE
Weasyprint version incompatability:  no format=pdf option

### ISSUE THREAD

**Issue by j-bbr** [nano-byte/Razor2Pdf#16]
Newer [versions](https://doc.courtbouillon.org/weasyprint/stable/api_reference.html#command-line-api) of weasyprint don't have the option used in the pdf renderer [here](https://github.com/nano-byte/Razor2Pdf/blob/e443f42a596e7e742afdbfa7618b273ae2383997/src/Razor2Pdf/PdfRenderer.cs#L33) anymore so pdf generation fails. Maybe the arguments to weasyprint could be made configurable?

**Comment by bastianeicher** [comment]
Thanks for reporting this issue! Will try get this addressed soon.

Do you happen to know what the equivalent replacement for `--format=pdf - -` would be?

**Comment by j-bbr** [comment]
If I understand this documentation from an [older weasyprint version](https://doc.courtbouillon.org/weasyprint/v0.42.3/api.html#command-line-api) correctly then there was a choice to output the file as a png instead of a pdf? If that's the case then I believe the png option disappeared and format=pdf became the default

**Comment by bastianeicher** [comment]
For simplicity's sake, I've opted to just remove the `--format=pdf` parameter completely (see 65d4f38de8e49249bbe39e43d4139d8ee3e4d192), basically forcing an upgrade of Razor2Pdf and Weasyprint together.

I've released a [new version of Razor2Pdf](https://github.com/nano-byte/Razor2Pdf/releases/tag/0.3.0) along with [new versions of the weasyprint/aspnet-core Docker image](https://hub.docker.com/r/weasyprint/aspnet-core/tags).

**Comment by j-bbr** [comment]
Thank you!
