### ISSUE TITLE
Support for creating PDF for views without ViewModel?

### ISSUE THREAD

**Issue by metapone** [nano-byte/Razor2Pdf#2]
`IPdfRenderer.RenderAsync` requires a model to be usable. For Razor Views without a view model, I have to create and pass a dummy model for RenderAsync to run. Could you make a `RenderAsync` with viewpath only?

**Comment by bastianeicher** [comment]
Good idea! I'll add an overload to `ReadAsync` in the next release.

**Comment by bastianeicher** [comment]
Implemented in 601fb543c3e1d0fa4f91e9858d3027b45a24b732 and released in [0.2.0](https://github.com/nano-byte/Razor2Pdf/releases/tag/0.2.0).
