### ISSUE TITLE
Error when creating PDF from Razor Page with Layout?

### ISSUE THREAD

**Issue by metapone** [nano-byte/Razor2Pdf#3]
Razor2Pdf doesn't recognized _Layout.cshtml in MVC Web Application, and explicitly specifying layout through `@{ Layout="~/Views/Shared/_Layout.cshtml"; }` throws an exception:

`Could not find an IRouter associated with the ActionContext. If your application is using endpoint routing then you can get a IUrlHelperFactory with dependency injection and use it to create a UrlHelper, or use Microsoft.AspNetCore.Routing.LinkGenerator.`

**Comment by bastianeicher** [comment]
Thanks for reporting this issue. I'll look into it and get back to you.

**Comment by bastianeicher** [comment]
Fixed in 98153f0413da983b8901a392ede8c3c48a7b283e and released in [0.2.0](https://github.com/nano-byte/Razor2Pdf/releases/tag/0.2.0).
